services:
  web:
    image: nginx:1.23.0
    container_name: web
    depends_on:
      - frontend
      - backend
    links:
      - frontend
      - backend
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  frontend:
    image: node:18.9.1
    environment:
      - REACT_APP_API_URL=http://bonne-coordination.st.ie.u-ryukyu.ac.jp/api
    container_name: frontend
    volumes:
      - ./frontend/bonne-coordination:/projects/frontend/bonne-coordination
    ports:
      - 3000:3000
    working_dir: /projects/frontend/bonne-coordination
    tty: true
    command: bash -c "npm i && npm start"
  backend:
    image: golang:1.19.1
    container_name: backend
    working_dir: /app
    env_file: .env
    environment:
      - POSTGRES_DB=postgres
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./backend:/app
    ports:
      - 8080:8080
    tty: true
    command: go run .
  db:
    image: postgres:14.4
    container_name: db
    restart: always
    env_file: .env
    environment:
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
    volumes:
      - ./db/init/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./db/backup:/backup
    ports:
      - 5432:5432
    tty: true
