CREATE TABLE users (
    id SERIAL NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    does_have_body_type BOOLEAN NOT NULL DEFAULT FALSE,
    gender VARCHAR(255) NOT NULL DEFAULT '',
    body_type VARCHAR(255) NOT NULL DEFAULT ''
);
