name: Deploy
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: ${{ secrets.SSH_CONFIG }}
      - name: Set env
        uses: SpicyPizza/create-envfile@v1.3
        with:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      - name: Check out code
        uses: actions/checkout@v2
      - name: Deploy with rsync
        run: |
          rsync -auvPz ./ ${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/bonne-coordination/
          ssh ${{ secrets.SSH_HOST }} 'cd /home/$USER/bonne-coordination; docker-compose down;  docker-compose -f docker-compose.prod.yml up -d --build'
